options:
  machineType: "N1_HIGHCPU_32"
timeout: 1800s
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--target', 'graph-node-build',
         '-t', 'gcr.io/$PROJECT_ID/graph-node-build:1',
         '-f', 'docker/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--target', 'graph-node',
         '-t', 'gcr.io/$PROJECT_ID/graph-node:1',
         '-f', 'docker/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--target', 'graph-node-debug',
         '-t', 'gcr.io/$PROJECT_ID/graph-node-debug:1',
         '-f', 'docker/Dockerfile', '.']
images:
  - 'gcr.io/$PROJECT_ID/graph-node-build:1'
  - 'gcr.io/$PROJECT_ID/graph-node:1'
  - 'gcr.io/$PROJECT_ID/graph-node-debug:1'
